# Generated by Django 5.2.5 on 2025-08-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='linkedin_url',
        ),
    ]
