# Generated by Django 5.2.5 on 2025-08-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_linkedin_url'),
        ('resumes', '0004_remove_all_linkedin_fields'),
    ]

    operations = [
    ]
